name: mono_model

opacity_mapping:
  initial: 0.0
  final: 0.0
  warm_up: 1

num_depth_candidates: 128
num_surfaces: 1

gaussians_per_pixel: 1

gaussian_adapter:
  gaussian_scale_min: 0.5
  gaussian_scale_max: 15.0
  sh_degree: 4

d_feature: 64

# kept for compatibility with main.py debug print
monodepth_vit_type: vits

# params for multi-view depth predictor
unimatch_weights_path: "checkpoints/gmdepth-scale1-resumeflowthings-scannet-5d9d7964.pth"
multiview_trans_attn_split: 2
costvolume_unet_feat_dim: 128
costvolume_unet_channel_mult: [1,1,1]
costvolume_unet_attn_res: [4]
depth_unet_feat_dim: 32
depth_unet_attn_res: [16]
depth_unet_channel_mult: [1,1,1,1,1]
downscale_factor: 4
shim_patch_size: 4

# ablations
wo_depth_refine: false
wo_cost_volume: false
wo_backbone_cross_attn: false
wo_cost_volume_refine: false
use_epipolar_trans: false

# voxelization branch
enable_voxelization: false
use_plucker_embedding: true
voxel_feature_dim: 32
gaussians_per_cell: 4
down_strides: [2, 2]
cell_scale: 1.0
cube_merge_type: mean
voxelization_downsample_factor: 2
voxel_max_points_per_batch: 65536
voxel_conf_threshold: 0.05
profile_voxelization: false
voxel_compute_2d_branch: false
voxel_low_vram_arch: false
voxel_train_depth_predictor: true
return_depth: true
